### ISSUE TITLE
Bürozeiten

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#100]
Das Layout der Bürozeiten anpassen. Also entweder in unserem kleinen Bilderrätsel oder dann ganz normal, wie es jetzt auch schon ist. Nur dann nicht so komisch ausrichten bitte.

**Comment by aschle** [comment]
![openinghours](https://cloud.githubusercontent.com/assets/883797/13401338/055f7030-df0c-11e5-8409-00a9947ca258.png)

Nummer 3

**Comment by aschle** [comment]
@julimage leider hab ich erst am Ende gemerkt das mein Photoshop-Draft ungenau war. Das muss ich nochmal nachbessern, die einzelnen Zeiten sind nicht gleichbreit. Du kannst wenn du große Lust hast machen, die 7 ist auch noch abgeschnitten. Naja mach ich wenn dann später.

**Comment by aschle** [comment]
wenn man die seite kleiner macht, dann klappt das mit dem hover auch noch nicht, son scheiß
