### ISSUE TITLE
Text im Header

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#101]
Ich finde, die Zeilen über dem Headerbild sollten dieselbe Überschrift haben wie die im Slider. Nicht die Überschrift `<h4>` sondern die darunter, z. B. "Im Schadensfall unterstützen wir Sie zu 100%." (Ist in einem `<span>` - hat keine Überschriftentypisierung?!

**Comment by aschle** [comment]
http://goo.gl/2OPWVa

schrif gröesser und duenn wie slider
