### ISSUE TITLE
Header- und Sliderbilder verkleiner

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#107]
... die sind momentan zu groß. 1 MB pro Bild ist doch Nonsens.

**Comment by aschle** [comment]
@julimage wollen wir das gleich mit machen?

**Comment by womak24** [comment]
https://medium.freecodecamp.org/a-guide-to-responsive-images-with-ready-to-use-templates-c400bd65c433

**Comment by womak24** [comment]
ich glaube die bilder generell schon mal kleiner zu machen, würde schon mal viel bringen, am ende kann so ein Bild 200KB haben, mehr aber denke ich nicht.

**Comment by julimage** [comment]
Ja, mach ich nach meinem Urlaub!
