### ISSUE TITLE
SMTP ändern

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#110]
FORMULAR SCHADEN MELDEN
Dazu gab es bereits eine E-Mail. Wie wollten wir das mit dem SMTP machen? Gerade läuft es über einen extra google mail account. Das soll sicherlich so nicht bleiben, bzw. muss weitergeleitet werden. Das muss wirklich dringend geklärt werden.

**Da vermittelt Karsten einen Kontakt zwischen Bernd und Alexa. Aber erst nach dem Urlaub. Jetzt geht es erst mal so und alles prima.**

**Comment by aschle** [comment]
@julimage guck mal was ich hier gefunden habe. Nach dem Urlaub war wohl noch nicht :D

**Comment by MSCL** [comment]
Ich habe den Code soweit gefixt, mit meinen Persönlichen Mail Server Daten von Bernd (elbe-elster) funktioniert es auch. Via Google bekomme ich einen Login Fehler, also der Username oder das Passwort im Code :D sind falsch.

Man muss mir mal die richtigen Login Daten geben damit ich das einrichten kann.

**Comment by julimage** [comment]
Wir dürfen keine Google-Mail-Adresse mehr nutzen. Also keine für irgendwelche Weiterleitungen etc. Deshalb hat Bernd eine neue Adresse eingerichtet. Ich schick dir das mal per Mail an deine Elbe-Elster-Adresse, denn um Himmels willen soll ich das Dokument bloß nicht mit Google verschicken und auch an keine Google-Adresse.... Ich hab's mir nicht ausgedacht. :-)

**Comment by MSCL** [comment]
Naja gut, jetzt fehlt nur noch der SMTP Server?!

**Comment by julimage** [comment]
Habe mit Alexa vorhin besprochen, dass du mit Bernd sprichst bzw. ihn kontaktierst. Wenn ich ihn anrufe dann will er mir vermutlich einreden, dass wir das alles nicht brauchen oder so... Sowas in der Richtung hatte ich schon mal. Und da ich da auf dem Gebiet keinen Plan hab, kann ich dann dazu nichts konstruktives beitragen

**Comment by MSCL** [comment]
Habe mit Bernd telefoniert, funktioniert alles (Habe es auf meine persönliche Mail-Adresse schicken lassen zum testen). Bitte nach dem Eintragen des Passworts nochmal mit der finalen Mail-Adresse testen!
