### ISSUE TITLE
Darstellung: Telefonummer/Fax 

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#112]
**Bernd: Telefonummer / Fax überall immer mit internationaler Schreibweise - Bernd empfiehlt immer die Outlook Schreibweise ( international, schon zu nutzen) +49 (0)3533 4826-0**

Wir: Zum Darstellen von Telefonnummern gibt es die DIN 5008, an die wir uns gehalten haben:
Telefonnummern mit Vorwahl: 03533 48260
Telefonnummer mit Vorwahl- und Durchwahlnummer: 03533 4826-0 (falls es denn eine Durchwahl wäre)
Telefonnummern im Schriftverkehr mit dem Ausland: +49 3533 4826-0

Wenn ihr viele Kunden aus dem Ausland habt, dann wäre die internationale Schreibweise schon sinnvoll, ansonsten ist diese Schreibweise heutzutage eher ungebräuchlich. Falls du aber auf die internationale Schreibweise bestehen solltest, dann würden wir sie nach DIN 5008 angeben, also: +49 3533 4826-0

**Karsten: Kunden aus dem Ausland gibt es nicht, aber viele Kunden rufen aus dem Ausland an, wenn sie z. B. Autounfall haben oder im Ausland krank geworden sind. Das bedeutet, dass es funktionieren muss, wenn man auf die Nr. klickt. Also hinterlegt sein muss die korrekte internationale Telefonschreibweise. Aber was angezeigt wird kann ruhig so sein, wie wir es bereits darstellen. Aber ich glaube, das ist ja bereits so. Müsste man nochmal prüfen.

Karsten hat noch angemerkt, dass wenn er auf die Telefonnummer klickt, auf dem Desktop, dass er dann vom Browser rausgeschmissen wird. Ist ja klar. Wenn ich da drauf gehe will Chrome auch ne App starten… Können wir den Telefonnummerlink für Desktopgeräte nicht ausschalten? Damit da keiner sinnlos rumklickt und sich aufregt, dass da nix passiert?

Dass man auch von Skype anrufen können soll, das war wohl noch wichtig. Kann man das verbinden?**

**Comment by aschle** [comment]
OK ich kann in der Desktopversion die Telefonnummer nicht als LINK stylen. Dann wäre es aber auch in dem blauen Balken kein Button mehr sondern normaler weißer Text.

Das mit Skype verstehe ich nicht das Attribut "callto" ist kein Standart. Wer bitte ruft mit Skype an? Soll sich dann automatisch skype öffnen, wenn man es hat, das finde ich eher nervig. Kann man mit Skype festnetznummern anrufen? Was ist dann mit GoogleHangouts, soll man das auch gleich unterstützen dann?

**Comment by aschle** [comment]
@julimage Ist das hinfällig oder noch relevant?

**Comment by MSCL** [comment]
Important todo!

**Comment by julimage** [comment]
@MSCL wie kommst du jetzt darauf?

**Comment by MSCL** [comment]
Wir waren gestern bei Bernd und haben nochmal ein paar ToDos bekommen, die ich abarbeiten werde. :)

**Comment by MSCL** [comment]
@aschle Ist es nicht best practice alle Telefonnumern, welche auf der Seite auftreten (welche sich ja auch mal ändern können, wie in unserem Fall jetzt) in einer globalen Datei abzulegen, damit man NICHT das gesamte Projekt nach den Nummern durchsuchen muss um diese zu ändern? Das ist jetzt schon prädestiniert dafür Fehler zu machen und um Dinge zu übersehen!

Zusätzlich werden die Nummern, wie Variablen, an mehreren Stellen angezeigt/ benutzt und sollten deshalb auch schon zentral aus einer Datei abgegriffen werden um nicht inkonsistent verändert werden zu können?

**Comment by MSCL** [comment]
Laut Bernd gibt es gute Gründe alles auf https://en.wikipedia.org/wiki/E.123 (international) umzustellen. Ich würde auch die Darstellung und tatsächlich hinterlegte Nummer konsistent halten.
