### ISSUE TITLE
Widerrufsrecht ergänzen

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#116]
Karsten: WIDERRUFSRECHT – sollten wir inhaltlich ausführlicher untersetzen ( ich muss dazu mal schauen, was der Gesetztgeber mindestens dazu verlangt oder vorschreibt)

--> Inhalt folgt später

**Comment by aschle** [comment]
@julimage Das ist DONE oder?

**Comment by womak24** [comment]
Das könnte man gleich mal mit erledigen, falls da die Texte nur irgendwo rumliegen.

**Comment by MSCL** [comment]
Hier habe ich keine Ahnung, ich würde sagen das stimmt so oder? Vlt könnte man die Kontaktdaten als Links mit in den Text packen. Prinzipiell stehen die aber auch direkt drunter.
-> Issue schließen?!

**Comment by julimage** [comment]
Das Widerufsrecht, Impressum und DSE habe ich alles im Zuge der neuen DSGVO im Mai/Juni umgesetzt. Das ist alles soweit aktuell.
