### ISSUE TITLE
gMaps korrigieren

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#118]
Karsten: Hauptsitz Elsterwerda / Routenplaner ist rot die „WOMAK GmbH Der Gebäudeversicherungsmakler“ zu finden, was aber die andere Firma ist und nicht WOMAK 24…, wenn es korrekt sein soll.(die selbige Adresse ist es ja)

Hier gibt es ein Problem mit google. Ihr habt eure Firma nicht eingetragen. Die Adresse ist mit Frank Müller Versicherungsmakler GmbH verknüpft. Das müsste man ändern, also das müsstet ihr machen, schätze ich.

**Karsten hat eingetragen. Aber das dauert nun noch mit der Verifizierung usw. Also können wir erst in ein zwei Wochen fertig stellen.**

**Comment by aschle** [comment]
@julimage Jetzt müsste man hier ja das ganze beenden können, oder ist das auch schon zufällig DONE?

**Comment by womak24** [comment]
@julimage Das ist fertig, oder?

**Comment by julimage** [comment]
Ja, fertig.
