### ISSUE TITLE
Einbindung des Kundenmagazins anpassen

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#123]
DSGVO fordert, dass wir zumindest die Datenschutzhinweise um die Verwendung von Iframes erweitern.
Durch iFrames werden personenbezogene Daten an Dritte übermittelt (IP, usw.).
Ein Frage ist wo der Server der Drittanbieter steht (in EU oder außerhalb von EU).

Zum nachlesen:
* https://www.webseitenschutzpaket.de/urteile/iframes-haftung-bei-einbindung-externer-inhalte/

Ich sehe folgende Lösungen:
1) iFrame drin lassen: Daraus folgt, dass die Datenschutzhinweise angepasst werden müssen. Man muss herausfinden was genau angepasst werden muss. Herausfinden wo der Server steht (EU oder ausserhalb) und herausfinden welche Daten genau übermittelt werden.

2) iFrame komplett wegschmeißen. Dann muss man sich überlegen, wie der Platz dann genutzt werden soll, weiß kann er ja nicht bleiben. Hier muss eine Idee/Vorschlag her.

3) iFrame wegschmeissen und HTML Version vom Kundenmagazin an die Stelle pappen. Man muss herausfinden wie man an die HTML Version kommt. Evtl. reicht dazu einmal händisch das iFrame (da muss es ja eine URL) geben aufzurufen und das HTML händisch zu kopieren, bei uns pasten. Fertig.

Welche Lösung möchten wir machen. Hier bedarf es einer Entscheidung.

**Comment by julimage** [comment]
Es wurde abgestimmt, das iframe zu entfernen. Zitat von O. Ziesche: "ich habe zu Ihrer Mitteilung Rücksprache mit Herrn Schlegel gehalten und wir haben abgestimmt, dass die Einbindung
der Kundenzeitung als PDF Datei völlig ausreichend ist. Bitte veranlassen Sie dazu alles notwendige."

Ich habe das iframe bereits entfernt, ich fände es aber besser, wenn man nun die pdf-Downloads im Contentbereich hat und rechts als Sidebar, wie immer, dieses Pro-Womak-Akkordeon. Kannst du das bitte einbauen?
