### ISSUE TITLE
Kontaktformular - Checkbox

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#125]
Bitte folgendes erledigen:

- [x] Checkbox integrieren
- [x] Hinweis neben Checkbox integrieren (Einwilligung)
- [x] Text zum Formular in Datenschutzerklärung aufnehmen (Umgang mit Daten aus Formular)
- [ ] Checken ob das Formular immer noch funktioniert

Vorlage für Checkbox und Text:
<img width="798" alt="screen shot 2018-06-17 at 15 07 20" src="https://user-images.githubusercontent.com/883797/41508139-2fe973f4-7240-11e8-92d3-745477f5e14d.png">

**Comment by aschle** [comment]
@julimage Wenn IT-Recht-Kanzlei ein Kontaktformular bereitstellt und ein KEINE Checkbox gibt, warum brauche wir dann eine Checkbox, das verstehe ich nicht.

**Comment by aschle** [comment]
@julimage Ich habe nun verstanden und der folgende Text fasst das Ergebnis des OLG Kölln sehr gut zusammen: https://www.e-recht24.de/news/abmahnung/10651-abwarnung-kontaktformulare-einwilligung.html

Aufgrund des so genannten fliegenden Gerichtsstandes könnten Abmahner zur Klärung dieser Frage aber stets Kölner Gerichte anrufen.

So gehen Sie als Webseitenbetreiber bei Kontaktformularen 100% auf Nummer sicher:

    Fügen Sie Ihrer Datenschutzerklärung einen Passus zum Umgang mit Daten aus dem Kontaktformular hinzu.

    Binden Sie eine Checkbox unter dem Kontaktformular ein.

    Fügen Sie neben der Check-Box einen Einwilligungstext zum Umgang mit den Daten der Nutzer und Ihr Recht auf Widerspruch ein.

Vorgehen von diesem Beitrag:

Für den Einwilligungstext finden Sie eine Vorlagen bei eRecht24 Premium.

**Comment by julimage** [comment]
OK, auf dem Server läuft's. Ich habe jetzt mal testweise ausgefüllt und abgeschickt. Mit der Bitte, mir eine Bestätigung zurück zu mailen.

Was doof ist, dass es keine Bestätigung gibt, dass das Formular abgeschickt wurde. Nachdem ich auf senden geklickt habe, wird die Seite neu geladen und die Felder sind mit meinen letzten Angaben vorausgefüllt...

**Comment by aschle** [comment]
Ich habe das auch gerade mal abeschickt. Und habe mich auch gewundert, dass es keine Bestätigung gibt. Gab es die nicht mal? (ich frage mal Immi wo das hin ist) An welche emailadresse wird das eigentlich gesendet? Bzw. mit welcher wird das versendet? Immernoch mit Googel, ich glaube ich hatte da Bernd ne Mail geschickt, ach so hier die Antwort dazu:


* (3) Und was noch wichtig ist: Wir dürfen die Mails nicht über die Googleadresse weiterleiten. Das wollen die Makler nicht und laut Datenschutz geht das wohl nicht. *

​Das ist richtig, diese temporäre Lösung sollte durch etwas Vernünftiges ersetzt werden. Ich habe im Kopf, dass es technisch zu dem Zeitpunkt aus irgendwelchen Gründen nicht anders ging.

Welche Lösung würdest du hier vorschlagen?

Bernd: Du kannst ja eine PHP Datei schreiben, welche den Mailversand zum lokalen Mailserver auf womak24.de durchführt. Und wir richten eigens einen Mail-Account dafür ein.

**Comment by MSCL** [comment]
Das Formular müsste prinzipiell erstmal wieder wie gewohnt funktionieren, da waren ein paar kleine Fehler drinnen. (Nach jedem fehlerhaften Submit wird immernoch in jedem Feld ein Space angehangen, ka. wieso). Checkbox mit Text und zugehöriger Funktionaität (Submit Button wird auch enabled/ disabled) war schon implementiert. Das Google Re-Captcha befindet sich zwar schon auf der Seite wird aber innerhalb der Form nicht beachtet.

**Comment by julimage** [comment]
Also reparierst du das noch und bastelst es so, dass das Re-Captcha auch angewandt werden muss?!

**Comment by MSCL** [comment]
Ja ich versuche es. @aschle ich brauche mal den SecretKey des ReCaptchas um den Code zu ergänzen, sonst kann ich das Ergebnis nicht abfragen?

**Comment by MSCL** [comment]
Das Kontaktformular sollte jetzt fertig sein. Das ReCaptcha ist leider kein reguired-field im Form, sprich man kann auch ohne es zu beantworten den Abschicken-Button drücken, aber abgesendet wird die Mail dann erst wenn auch das Captcha gelöst wurde. Dazu gibt es wie zu den anderen Feldern auch normale Fehlerausgaben. Ich wollte jetzt nicht noch anfangen im JavaScript rumzuschreiben.
Neues ReCaptcha Zeug: https://www.google.com/recaptcha/admin#site/342991687?setup

**Comment by MSCL** [comment]
Wenn euch das so reicht (ohne JavaScript) sollte der Issue auch geschlossen werden können.

**Comment by julimage** [comment]
So lange der Benutzer weiß, dass das Formular nicht abgeschickt ist, dann ist noch bestimmt alles gut?!

**Comment by MSCL** [comment]
Jop, ihr könnt es ja nochmal überprüfen! :)
