### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#126]
Es hieß ja als Hinweis bei recht24 folgendes, wenn man Google Web Fonts nutzt:

"Das Einbinden der Funktionalitäten und Plugins von Google Maps / Google Web Fonts auf Websites ist in Deutschland nicht ohne rechtliches Risiko möglich, da hier unter Umständen ungefragt Daten der Websitebesucher an den Anbieter des Dienstes übertragen werden. Nach Ansicht einiger Gerichte und Datenschutzbehörden genügt dafür ein Hinweis in der Datenschutzerklärung nicht. Empfohlen wird hier eine ausdrückliche Einwilligung der Nutzer."

- Vielleicht sollten wir die Fonts herunterladen und auf dem Server speichern und dann einbinden. Das geht ja auch. Aber ist halt nachträglich ganz schön aufwändig?

**Comment by aschle** [comment]
@julimage Habe Open Sans nun lokal im Font Ordner gespeichert und wir nun lokal eingebunden. D.h. nicht mehr von Google runtergeladen. Ich denke nun kann man auf den Hinweis im Datenschutztext auch verzichten. Ich nehme das also dort raus.
