### ISSUE TITLE
gMaps

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#127]
Es hieß ja als Hinweis bei recht24 folgendes, wenn man Google Maps nutzt:

"Das Einbinden der Funktionalitäten und Plugins von Google Maps / Google Web Fonts auf Websites ist in Deutschland nicht ohne rechtliches Risiko möglich, da hier unter Umständen ungefragt Daten der Websitebesucher an den Anbieter des Dienstes übertragen werden. Nach Ansicht einiger Gerichte und Datenschutzbehörden genügt dafür ein Hinweis in der Datenschutzerklärung nicht. Empfohlen wird hier eine ausdrückliche Einwilligung der Nutzer."

- Gibt es ne Alternative? Eigentlich nicht wirklich, deshalb würde ich es eigentlich lassen. Den Hinweis in der Datenschutzerklärung habe ich ja drin.

**Comment by aschle** [comment]
Es gibt keine Alternative, auch OpenStreetMap sendet Daten an irgendwelche Server. Ich finde wir müssen Womak24 darauf hinweisen. Die müssen die Entscheidung Treffen, ob GoogleMaps bleibt oder nicht. Also wir lassen es erstmal so wie es ist, aber die müssen das wissen, wenn die dann wollen nehmen wir es raus. Malen eine eigene Karte und packen da ein Link zu GoogleMaps hin, fertig.

@julimage Was meinst du?

**Comment by womak24** [comment]
@julimage Das ist doch Done oder? Ich erinnere mich an eine Diskussion. Was war da der Kompromiss?

**Comment by julimage** [comment]
Naja, die Diskussion wurde nicht richtig beendet. Wir fanden es super, dass man gmaps hat und nicht tausend mal klicken und selber suchen, wenn man die Adresse auf der Karte sehen will. Herr Ziesche hat irgendwie bammel. Aber nachgefragt hatte er auch nie wieder.

Ich habe auch noch noch auf anderen großen ähnlichen Seiten geguckt, die haben oft gmaps eingebettet. Und in der DSE den entsprechenden Hinweis. Das haben wir auch so. 

Wenn jetzt von womak nicht noch mal jemand was sagt, lassen wir es. Deshalb: done.
