### ISSUE TITLE
Robots.txt anlegen

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#131]
Also die brauchen wir.

Z.B. Impressum und auch Datenschutztexte sollten nicht von einer Suchmaschine indexiert werden.
Und auch nicht diese PW dateien :D

**Comment by julimage** [comment]
OK, diese müsstest du dann schreiben. Die PW-Dateien sind gar nicht mehr auf dem Server. Die brauchen wir für das Formular bestimmt nicht. Wär ja Quatsch :-)

**Comment by MSCL** [comment]
Ich habe eine robots.txt angelegt. Nicht indexirt werden jetzt impressum, erstinformation, datenschutz und widerrufsrecht.

**Comment by MSCL** [comment]
Und ein bisschen mehr, was ich als sinnlos zum indexieren erachtet habe. Der Issue sollte geschlossen werden können.
