### ISSUE TITLE
HTTP -> HTTPS

### ISSUE THREAD

**Issue by MSCL** [womak24/womak24.github.io#132]
Alle Links von HTTP zu HTTPS umstellen.

**Comment by MSCL** [comment]
Ist es nicht best practice alle Links, welche auf der Seite auftreten (welche sich ja auch mal ändern können, wie in unserem Fall jetzt) in einer globalen Datei abzulegen, damit man NICHT das gesamte Projekt nach "HTTP" durchsuchen muss um es zu HTTPS zu ändern? Das ist jetzt schon prädestiniert dafür Fehler zu machen und um Dinge zu übersehen!

**Comment by julimage** [comment]
Der Server leitet doch immer automatisch nach https um... Insofern... Aber kann man ja mal machen. Wie das mit der globalen Datei zu verstehen ist, kann ich nicht ganz folgen. Da die Seite nicht so umfangreich ist finde ich es nicht so wild, jetzt einmalig das Projekt durchzusuchen. Macht die Suchfunktion ja eigentlich auch schön automatisch...

**Comment by MSCL** [comment]
Ja das stimmt, laut Bernd sollte das trotzdem mal angepasst werden. Ein Bug, der daraus resultierte, ist das die Map auf dieser Seite nicht mehr geladen wird. -> https://womak24.de/kontakt/berlin/

**Comment by julimage** [comment]
Ah ok, deshalb :-) Hatte ich auch schonmal gesehen... Aber da ich eigentlich bei der Kartenfunktion eine bessere Lösung einbauen wollte, hatte ich es vertagt. Ich wollte die Karte erst nach einem Klick sichtbar machen, sodass sich der Server nicht gleich mit google verbindet...  Wegen der DSGVO und so...

**Comment by MSCL** [comment]
Ah ok, na ich habe jetzt ersmal als vorübergehenden Fix die Adresse auf HTTPS geändert.
