### ISSUE TITLE
Update Copyright

### ISSUE THREAD

**Issue by MSCL** [womak24/womak24.github.io#134]
Copyright von 2018 auf 2019 umstellen.

**Comment by MSCL** [comment]
Ich kenne mich hier nicht genau aus.
@julimage Das Copyright-Sign befindet sich nur einmal im Footer auf der gesamten Webseite?

**Comment by MSCL** [comment]
Ich kenne mich nicht so gut mit Jekyll aus, aber dieser Code im Footer sieht so aus, als ob beim bauen der Seite das Jahr automatisch geupdatet wird? Zeile 43 im Footer.html `<li>© 20{{ site.time | date: '%y' }}</li>`

**Comment by julimage** [comment]
Eigentlich sollte der automatisch geupdatet werden, ja. Habe ich mal so gebaut und es hatte auch funktioniert, Warum diesmal nicht, keine Ahnung. Aber der Footer ist zwei oder dreimal zu ändern, da es verschiedene Templates gibt.

**Comment by MSCL** [comment]
Naja vlt. wurde die Seite dieses Jahr noch nicht neu gebaut und online gestellt?

**Comment by julimage** [comment]
Dieses Jahr habe ich tatsächlich noch nichts hochgeladen aber ich dachte eigentlich, dass diese Zeile eben immer beim aufrufen der Seite aufgerufen und das Jahr generiert wird? Anfang 2018 hatte ich das jedenfalls so geändert und es hatte funktioniert.

Wenn ich die Seite lokal aufrufe funktioniert es auch...

**Comment by MSCL** [comment]
Das ist natürlich unschön.

**Comment by MSCL** [comment]
Ich habe mir das nochmal angeschaut. In der Datei footer.html werden in den Zeilen 27 sowie 43 der Befehl `site.time` verwendet. Dieser gibt die aktuelle Zeit beim `build` bzw. `serve` Befehl aus. Nach dem nächsten update der Seite sollte also alles wieder stimmen. Bei mir local steht jetzt auch 2019 da.

**Comment by julimage** [comment]
Das heißt, die Seite muss also zu Beginn jedes neuen Jahres einmal "neu gebaut" und online gestellt werden? Da gibt es nix, was das dauerhaft selbstständig macht, ohne dass man die Seite aktualisisert?
