### ISSUE TITLE
Globale Fixed Value Datei

### ISSUE THREAD

**Issue by MSCL** [womak24/womak24.github.io#136]
Um Veränderungen von Links und Telefonnumern und der gleichen in Zukunft einfacher zu gestalten würde ich vorschlagen, Dateien anzulegen aus der man diese Werte ausliest.

**Comment by MSCL** [comment]
Jedenfalls macht man das in anderen Bereichen der Software-Entwicklung so. Ist das bei Web anders, beziehungsweise nicht möglich?

**Comment by julimage** [comment]
Auch hier, diese Webseite ist eigentlich so klein und es gibt überschaubare Telefonnummern und Links, sodass ich extra Dateien da irgendwie überflüssig finde... Aber ich bin da ja nun kein Programmierprofi und insofern würde ich es einfach den Profis überlassen :-)

**Comment by MSCL** [comment]
Ich kann ja mal schauen, wie aufwendig so etwas wäre und nochmal auf Alexas einschätzung warten.

**Comment by MSCL** [comment]
Ich habe das jetzt erstmal in die _config.yml geschrieben
