### ISSUE TITLE
footer (4 graue spalten)

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#16]
vielleicht umdrehen, sodass hintergrund ganz hell grau und text dunkler damit besser lesbar, oder schrift dunkelgrauer, da es aber ein footer ist, daher fehlt gerade ein bisschen die abgrenzung zu den teaser-bubbels, vielleicht. zumindest in der mobile version

**Comment by pelzerim** [comment]
Sieht nicht so mega aus.
Hab deswegen ganz oben in _base setting-variablen eingeführt um das schnell wieder rückgängig zu machen:
$footer-bg-color: $gray-light;
$footer-text-color: white;
