### ISSUE TITLE
Über Uns mobile

### ISSUE THREAD

**Issue by pelzerim** [womak24/womak24.github.io#26]

**Comment by pelzerim** [comment]
@alexa-schlegel 
Das abschließen der bilder mit den menüs wird unterbunden durch 

.main {
  padding-top: 70px; // 0 damit bilder direkt abschließen mit menü
}

in z   51 in base.scss

Wenn dort auf 0 gesetzt wird, schließt es ab

**Comment by aschle** [comment]
auf 60 gesetzt
