### ISSUE TITLE
design: mobile; tel und email nebeneinander?

### ISSUE THREAD

**Issue by pelzerim** [womak24/womak24.github.io#30]
<img width="368" alt="womak24_gmbh" src="https://cloud.githubusercontent.com/assets/1674483/12677989/b1c8dc40-c69c-11e5-9090-0e531684f393.png">
die beiden nebenander anstatt unternandner?

**Comment by aschle** [comment]
@julimage ???

**Comment by aschle** [comment]
ist jetzt erstmal untereinander
