### ISSUE TITLE
Schadenbanner - Startseite

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#34]
- Bild einfügen (Mensch - ratlose frau)
- blau über die ganze Breite!

**Comment by aschle** [comment]
frau muss Jule noch ausschneiden

**Comment by aschle** [comment]
@julimage ich brauch noch diese schöne frauin freigestellt :)

**Comment by julimage** [comment]
Liegt im Ordner Dropbox, 02_Inhalte/02_Media/20160202_woman.png
