### ISSUE TITLE
Onlinemagazin umbenennen

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#35]
muss irgendwie anders heißen damit Neuigkeiten und Onlinemagazin als unterpunkte sind
unterpunkte ins menü machen

**Comment by aschle** [comment]
Untermenü:
- Onlinemagazin (oder besser **Kundenmagazin**) [PDF]
- **Neuigkeiten** || Blog || News

Ich würde den Oberpunkt **Aktuelles** nennen

Bei Barmer/AOK/DKB ist das meist mit unter **Kontakt & Service**.

Any ideas? @hackberd @julimage

**Comment by julimage** [comment]
Service find ich nicht schlecht. Ich hab es in den Layoutdateien jetzt aber erstmal als "Aktuelles" angelegt.

**Comment by aschle** [comment]
Ok heißt in Zukunft dann "Aktuelles". Muss erstmal geklärt werden, was genau mit diesem Blogartigen-Ding passieren soll. Wenn das erst in der Version 2.0 kommt, dann bleibt erstmal alles wie gehabt bei Kundenmagazin, ohne Unterseiten usw.

**Comment by julimage** [comment]
Kundenmagazin ist prima und da es keine News/Blog geben soll... aus die Maus. Close.
