### ISSUE TITLE
logo ohne unterzeile (Jule)

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#44]

**Comment by julimage** [comment]
Logo liegt in der Dropbox: 01_WOMAK24/02_Inhalte/03_CI/womak-logo-Bildmarke_72dpi.png

**Comment by julimage** [comment]
Logo liegt in der Dropbox: 01_WOMAK24/02_Inhalte/03_CI/womak-logo-Bildmarke_72dpi.png
