### ISSUE TITLE
Metadatenanpassen

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#5]

**Comment by julimage** [comment]
1. Keywords suchen, z. B. "Versicherungsmakler" "Berlin-Brandenburg"...
2. Description schreiben, die Google dann anzeigt (ca. 250 Zeichen)

**Comment by julimage** [comment]
**Vorschlag für Description**

Wir sind seit 1994 als Versicherungsmakler GmbH tätig und überzeugen mit Qualifikation, Termintreue und Verlässlichkeit, was von unserer traditionell langjährigen Kundschaft sehr geschätzt wird. Sprechen Sie uns an – wir sind jederzeit für Sie da.

**Comment by julimage** [comment]
**Keywords**

Womak24, Versicherungsmakler, Versicherungen, Berlin-Brandenburg, Berlin, Brandenburg, Risikoanalyse, Beratung, Immobilienversicherungen, Multihaftpflichtversicherung, D&O, Lohnkostenoptimierung, Altersvorsorge, VDVM, Verband Deutscher Versicherungsmakler, VEMA, Versicherungs-Makler-Genossenschaft, Elsterwerda, Karsten Schlegel

**Comment by julimage** [comment]
**Vorschlag II für Description**
Wir bieten Versicherungslösungen für Unternehmen. Hierbei überzeugen wir mit Qualifikation, Termintreue und Verlässlichkeit, was von unserer traditionell langjährigen Kundschaft sehr geschätzt wird. Sprechen Sie uns an – wir sind jederzeit für Sie da.
