### ISSUE TITLE
Scollverhalten Navigation

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#54]
- Blaue Leiste sollte nicht zur hälfte abgeschnitten werden
- entweder sobald man scollt springt die navigation oben ran oder
- erst nach einer weile anfangen das es scollt, nicht halb rüberscorllen also

**Comment by pelzerim** [comment]
Ausgetauscht durch bootstraps [affix](http://getbootstrap.com/javascript/#affix).

**Comment by aschle** [comment]
ist der alte code noch drin oder? zeile 1-14 kann also raus under zugehörige sass code also auch?

zeile `// Highlight current Menu item` kann auch raus?

**Comment by pelzerim** [comment]
Hier ist wichtig, dass wenn du die größe des headers oder der navbar veränderst, dass du dafür die passenden variablen benutzt (oben in _base)
