### ISSUE TITLE
Texte die ich noch nie gesehen habe

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#68]
- Qualitätssicherung
- Mitwirkungspflichten und Obliegenheiten
- Maklervollmacht, Datenschutz und Maklerauftrag

Wer soll die lesen und vor allem warum hätte ich Lust solche länglichen Texte zu lesen!?

Das Wort Obliegenheiten habe ich noch nieeee gehört.

**Comment by julimage** [comment]
Lohnkosten: Keine Grafik. Da kommt ein Text.
