### ISSUE TITLE
Footer Navi: Highlighten wenn man im Impressum ist

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#69]

**Comment by pelzerim** [comment]
JS fertig.
@aschle  Wie soll das aussehen? Hab erstmal nur underline gemacht. Siehe _base.scss Zeile 302

**Comment by aschle** [comment]
ja nur underline, aber eigentlich sollte man für das highlighten von menüpunkten kein JS brauchen, das ist doch einfach nur CSS

**Comment by pelzerim** [comment]
jup http://stackoverflow.com/a/19273580/2596452
