### ISSUE TITLE
Spruch auf Headerbild Unterseite auf das Bild

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#71]
ist grad noch als zeile untern drunter, sollte so sein wie bei slider, sollte auf mobild entweder weg sein oder unten drunter oder drüber rutschen, oder einfach weg

**Comment by pelzerim** [comment]
Hab einfach mal oben links in die bilder gemacht, Siehe .subside-img-text

**Comment by aschle** [comment]
jo sollen die doch erstmal sehen, dass da noch inhalte fehlen ... :0
