### ISSUE TITLE
Header Images: Größe verändern (Desktop)

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#80]
Wenn ich mir etwas wünschen darf: Bitte Headerbilder auf der Desktop-Variante vergrößern.

Von jetzt 150px Höhe auf bitte 234px --> also 9*baselineheight (baselineheight = 26px).

**Comment by julimage** [comment]
Bildzuschnitte sind in der Dropbox. In der bekannten Ordnerstruktur, die wir für die Tabelle gemacht haben. Headerbilder heißen sub.png, Sliderbilder heißen slider.png. (grün markiert)

**Achtung** bei den Dienstleistungen: sub_WDL.png ist für "Weitere Dienstleistungen", dazu dann auch das Sliderbild. Das Bild sub_DL.png ist für die "Verteilseite" Dienstleistungen".

**Comment by aschle** [comment]
hä das sind ja jetzt ne menge mehr pixel höhe... guck dir das mal in live an, und auch auf mobil, ich guck auch mal, hab noch nicht.
