### ISSUE TITLE
Unterschied zwischen Eda und Berlin unklar

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#83]
sollen Leute in Eda oder eher in Berlin anrufen?

**Comment by aschle** [comment]
was ist GENAU der unterschied zwischen den Standorten? soll ich wenn ich aus berlin bin lieber in Berlin anrufen, oder gibt es da inhaltliche Unterschiede?

**Comment by julimage** [comment]
Servicebüro meint Servicebüro, das bedeutet, man kann auch da anrufen. Gibt ja Telefonnummer (030 61202961) - Also natürlich alle die, die in Berlin und Umgebung sind rufen im Servicebüro an.

Hauptsitz mit Mitarbeitern ist halt in Eda. Ist auch Firmenstandort. Wenn du das für notwendig hältst, müssen wir bei Bürozeiten halt einen Satz einfügen, so nach dem Motto "Wenn Sie im Berliner Raum wohnen rufen Sie uns bitte an." - Aber dein Vater und ich fanden das ehrlich gesagt nicht nötig. Können wir ja nochmal reden.
