### ISSUE TITLE
man weiß nicht das ma die drei guten gründe aufklappen kann durch klicken

### ISSUE THREAD

**Issue by aschle** [womak24/womak24.github.io#85]
sieht man nicht, da muss man schon mutig sein :D

**Comment by aschle** [comment]
also entweder einen Pfeil nach unten oder so und dann lieber das Bild mit rein in das Textfeld ... oder so aber kein mensch weiß das man da draufklicken kann.

**Comment by julimage** [comment]
Dein Vater möchte gern, dass alle drei Boxen anfangs zugeklappt sind.

Die Pfeillösung ist sicher gut. Es kann so bleiben wie es jetzt ist, nur muss der Pfeil neben den letzten Buchstaben. Also so, wie es auch in der Navigation dargestellt ist. Kleines Dreieck mit Spitze nach unten, Spitze dabei auf der baseline.

**Comment by aschle** [comment]
Pfeil rechts daneben machen.

**Comment by julimage** [comment]
Pfeil ist gesetzt.
