### ISSUE TITLE
Formular "Schaden melden"

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#89]
1. Headerbild einfügen (s. Dropbox Ordner 08:Schaden melden/sub.png)
2. Feldbezeichnungen wie folgt anpassen:

Name --> Name, Vorname

Kontaktdaten für eine schnelle... --> Ihre aktuelle Telefonnummer und/oder E-Mail-Adresse

Die Rechenaufgabe: Wir müssen da noch was dazuschreiben, dein Vater hat erst nicht begriffen, was er überhaupt tun soll und auch nicht warum... Also vielleicht Sollten wir hinschreiben:

"Für eine sichere Übertragung Ihrer Daten tragen Sie bitte das Ergebnis in das nachstehende Feld."
Man kann den Satz ja auch in kleinerer Schrift in Klammern dahinter oder darunter setzen)

**Comment by aschle** [comment]
email von immanuel angucken und fixen
--> Ich habe das Problem weggewartet ... jetzt geht einfach plötzlich.

**Comment by aschle** [comment]
Mir ist immer noch nicht klar, was man bei Schadenszeitpunkt eintragen soll.

@hackberd : Bilder nur PNG, JPEG oder soll man da alles hochladen können? Wie ist das gerade so? Kann man da auch EXE Dateien verschicken? oder ZIP? Was ist die maximale Dateigröße? Ist man da Beschränkt auf irgendwas?

**Comment by aschle** [comment]
@hackberd Ich habe da doch noch eine Frage: Kann der Inhalt der Mail in die Mail oder muss das in einen extra HTML Anhang. Ich glaube nicht, das bei Womak jemand weiß wie man eine HTML Datei öffnet.

![email](https://cloud.githubusercontent.com/assets/883797/13554985/dfd20db0-e3b5-11e5-8ad5-bf5dce6234f9.png)

**Comment by aschle** [comment]
@hackberd Ah und noch was, nach dem Absenden erscheint eine Nachricht, von wegen erfolgreich abgeschickt, das ist ziemlich cool! Und warum ist das Formular noch befüllt mit meinen Daten? Und wenn ich die Seite neu lade dann stehen die Infos immernoch drin und die Email wird mir nochmal zugeschickt. Ist das so? Oder was hab ich falsch gemacht?

**Comment by aschle** [comment]
Wo kommt der Abstand dort her? Es scheinen Leerzeichen zu sein, aber ich hab keine Ahnung wie die da reinkommen :D 

![abstand](https://cloud.githubusercontent.com/assets/883797/13555089/db731a82-e3b7-11e5-86da-631fa911789b.png)

**Comment by aschle** [comment]
Vielleicht macht hier eher eine Zusammenfassung der Abgeschickten Daten Sinn? Find ich immer gut, damit man noch weiß (wenn man nicht sowieso eine Kopie bekommt) was man da so durch die Gegen geschickt hat.
![form](https://cloud.githubusercontent.com/assets/883797/13555096/f2a81eb4-e3b7-11e5-8c9a-29c6576a1675.png)

**Comment by aschle** [comment]
es wird kein PNG unterstützt.

**Comment by aschle** [comment]
das formular scheint nur abgeschickt zu werden, wenn man ein Bild anhängt.

**Comment by julimage** [comment]
Na Schadenszeitpunkt ist Datum und Uhrzeit. Was denn sonst? :-)
Am 06.03.2016 4:06 nachm. schrieb "Alexa Schlegel" <notifications@github.com

**Comment by aschle** [comment]
Na dann muss doch dort ein Datumsauswahlding hin und eine Uhrzeitauswahl und kein Textfeld. Geben die Menschen den Zeitpunkt Minutengenau an?

**Comment by julimage** [comment]
Naja. Nee. Vielleicht nur viertel, halb, dreiviertel und um. Die genaue
Uhrzeit ist da sicher nicht soooo relevant. :-)
Am 06.03.2016 8:02 nachm. schrieb "Alexa Schlegel" <notifications@github.com
