### ISSUE TITLE
Footer: Kompletter Firmenname

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#91]
Im Footer muss bei den Anschriften der vollständige Firmenname stehen. Also so:

STANDORT ELSTERWERDA
Womak 24 GmbH
Berlin-Brandenburg Versicherungsmakler
Elswald 3
04910 Elsterwerda

STANDORT BERLIN
Womak 24 GmbH
Berlin-Brandenburg Versicherungsmakler
Nassauische Straße 22
10717 Berlin

**Comment by aschle** [comment]
Hauptsitz Elsterwerda
Servicebüro Berlin
