### ISSUE TITLE
Logo auf der Startseite

### ISSUE THREAD

**Issue by julimage** [womak24/womak24.github.io#93]
Die Unterzeile kann man kaum lesen. Deshalb zwei Lösungsvorschläge:
1. Logo größer (Aber da haben wir das Problem, dass der ganze Bereich zu groß wird)
2. Logo ohne Unterzeile nutzen. Die Unterzeile dann gesondert anzeigen. In meinen Layouts hab ich diese Zeile bereits immer integriert. Schau mal bitte in die Scribbles. Da ist die Zeile "Versicherungslösungen für Ihr Unternehmen" oben im blauen Bereich (neben den Buttons). Wenn wir diese ändern zu "Ihr Berlin-Brandenburg Versicherungsmakler" - Was meinst du?

**Comment by aschle** [comment]
Unterzeile oben links hin machen
